### ISSUE TITLE
Tileset clipping support

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-omniverse#156]
Implement a method for clipping out sections of a tileset so that other data (eg. road designs, buildings, or higher detailed tilesets) can be displayed within.

Potential approaches include:
- Shader based removal similar to Cesium for Unreal
- Geometry based removal via boolean operations or similar

**Comment by r-veenstra** [comment]
The need for this is quite likely elevated with the release of Photorealistic 3D tiles.

A City Engine masterplan for an existing city - somewhat OK on the Cesium World Terrain

![capture 2023-05-25 10 40 47](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/0ea532ae-39a3-48fc-8377-d39cd0956bff)

However, when viewing in the context of the Photorealistic 3D tiles dataset we need to be able to clip out the existing for the proposed to a user defined shape.
 
![capture 2023-05-25 10 39 34](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/65a1c1a9-51b6-469b-a665-73f85ce83500)

There is probably a larger discussion to be had re: a consistent (potentially Cesium Native or even Cesium ion server side) based solution that works across ALL Cesium runtimes, as this problem is not unique to Omniverse alone.

**Comment by lilleyse** [comment]
Requested on the forum as well: https://community.cesium.com/t/cesium-google-maps-hide-some-selected-buildings/24225

**Comment by r-veenstra** [comment]
From an implementation point of view, it may make sense to use the BasisCurves to define a 2D polygon for clipping, however the issue with this is due to the lack of physics support on tilesets, the user has no way to click on and define the surface.

![image](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/672785f3-c0bb-47c1-a7ca-f1b79d64ab53)

**Comment by r-veenstra** [comment]
@corybarr looping you into this issue for upcoming clipping work.  I've done a little more testing on some potential pieces of the pussel.

For the BasisCurves in USD Composer, with Fabric enabled there are still some bugs such as not being able to see the curve when initially creating it, which is going to make this hard to use out of the box without tweaks.  However, we could still support a workflow where a user authors the curve outside of composer, which is common in many scenarios when you have complex shapes to clip.

Fundamentally I think Basis Curves are still probably the right foundation to build a cartographic polygon from, but we'll need to work though some issues.

Also, from my understanding the polygon rasterization happens in native, so that should streamline the implementation.

https://github.com/CesiumGS/cesium-native/blob/d3a2bbf4eac6c8bc7e6190f737c48ff370fab882/CesiumGeospatial/src/CartographicPolygon.cpp
https://github.com/CesiumGS/cesium-native/blob/d3a2bbf4eac6c8bc7e6190f737c48ff370fab882/Cesium3DTilesSelection/src/RasterizedPolygonsOverlay.cpp

I've also tested that adding a globe anchor to a Basis Curve works ok, as that is another fundamental component of being able to keep these polygons in line with a tileset.

**Comment by lilleyse** [comment]
@corybarr here are my thoughts on the USD / Fabric / MDL implementation.

Add a new USD class `CesiumPolygonImageryPrim` that inherits from `CesiumImageryPrim`. It should have the same options as [`CesiumPolygonRasterOverlay`](https://cesium.com/learn/unreal/unreal-clipping/) in Unreal, though not sure if "Material Layer Key" is relevant to us.  Add a `rel` attribute that references the polygon (most likely a `BasisCurves` prim). `CesiumPolygonImageryPrim` is added to the scene like regular imagery layers, as a child of a tileset prim.

Make sure to update `UsdNotificationHandler`, `Context`, `OmniTileset`, and related files so that addition/removal/changes to the prim are reflected back in our extension. Most of this should already by handled, except for the new attributes.

There shouldn't be many changes in `FabricMaterialDefinition` / `FabricMaterial`. `alphaMode` will need to be either `MASK` or `BLEND` if there are clipping polygons. Depends on whether cesium-native rasterizes polygons with feathered edges or not.

In `cesium_internal_imagery_layer_resolver` in `cesium.mdl` I think we'll need to return both the RGBA color (like it's doing now) plus the clipping alpha which would get applied in `compute_base_color`. Somehow we need to say whether an imagery layer's alpha is for color vs. clipping. Maybe an additional attribute to `cesium_internal_imagery_layer_lookup`.

Also note that you need to be in `RTX - Interactive` to see translucency.

Let me know if you have any questions along the way. I haven't actually used the clipping polygon feature so I could be missing a bunch of details.

**Comment by lilleyse** [comment]
> In `cesium_internal_imagery_layer_resolver` in `cesium.mdl` I think we'll need to return both the RGBA color (like it's doing now) plus the clipping alpha which would get applied in `compute_base_color`. Somehow we need to say whether an imagery layer's alpha is for color vs. clipping. Maybe an additional attribute to `cesium_internal_imagery_layer_lookup`.

Alternatively this functionality could be split into `cesium_internal_imagery_layer_resolver` and `cesium_internal_imagery_clipping_resolver` and the correct imagery layers assigned to each.

**Comment by corybarr** [comment]
>Also note that you need to be in RTX - Interactive to see translucency.

Am I incorrect thinking it will work with `Translucency -> Fractional Cutout Opacity` enabled in RTX Real-Time?

**Comment by lilleyse** [comment]
@corybarr yes, that should work as well

**Comment by r-veenstra** [comment]
@corybarr a quick screengrab of the dithering used in Unreal's clipping

As the tileset is loading in (coarse detail level)
![image](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/69ab283a-b89c-4084-98d1-fdf876ea49d1)

Once the tileset has loaded to full res
![image](https://github.com/CesiumGS/cesium-omniverse/assets/123468416/b5a99993-5c7b-4ea9-8559-c864b2bc0437)

Not critical to have for v1 but FYI as we prep blending code

**Comment by corybarr** [comment]
> Add a new USD class `CesiumPolygonImageryPrim` that inherits from `CesiumImageryPrim`. It should have the same options as [`CesiumPolygonRasterOverlay`](https://cesium.com/learn/unreal/unreal-clipping/) in Unreal, though not sure if "Material Layer Key" is relevant to us. Add a `rel` attribute that references the polygon (most likely a `BasisCurves` prim). `CesiumPolygonImageryPrim` is added to the scene like regular imagery layers, as a child of a tileset prim.

@lilleyse 

I think we'll also need a `CesiumCartographicPolygon` prim. We need to enforce a `rel` with a `BasisCurves` and a `GlobeAnchor`. See the Unreal implementation:
![image](https://github.com/CesiumGS/cesium-omniverse/assets/1040194/40a4754f-5b6a-4662-9e63-db5594fdf969)

Then the `CesiumPolygonImageryPrim` child would have a `rel` to the `CesiumCartographicPolygons` instead of `BasisCurves`:

![image](https://github.com/CesiumGS/cesium-omniverse/assets/1040194/afc1a09e-870c-4fec-832a-e74a252ada15)

**Comment by corybarr** [comment]
A `CesiumCartographicPolygon` seems likely to be useful for future features. For example, if I wanted to ask about offline classification results of the terrain type, I'd find a vector of `CesiumCartographicPolygons` useful as a query return type.
