### ISSUE TITLE
Zoom extents to tileset

### ISSUE THREAD

**Issue by r-veenstra** [CesiumGS/cesium-omniverse#192]
It would be great if we could select a tile set in the stage and zoom extents to it.

Currently, if you zoom extents to a tileset it zooms to its origin (usually at 0,0,0).

Simply having an AABB that matched the overall extents of the tileset (vs what is actually loaded) would suffice.  Particularly as a common use case for zoom extents is to simply find the tileset to begin with, and in those cases it may be so far away that no data is actually loaded.

**Comment by lilleyse** [comment]
Rough outline of the approach we discussed offline:

* Construct a `UsdGeomBoundable` on the tileset prim and create the extent attribute. This can happen in [`UsdUtil::defineCesiumTileset`](https://github.com/CesiumGS/cesium-omniverse/blob/824e9283cd9efa17ee9d75b0fe4760ba658b1b84/src/core/src/UsdUtil.cpp#L289-L316). The default values are fine, we'll set the actual extents later.
* After the tileset is loaded in `OmniTileset` get the root tile bounding volume. The bounding volume can be either a `box`, `region`, or `sphere` according to the 3D Tiles spec. Convert the bounding volume to an axis-aligned box in ECEF coordinates. Check if there's helper functions for doing this in cesium-native, otherwise check what exists in CesiumJS.
* Whenever the ECEF to USD transform changes (e.g. when the georeference origin changes) update the tileset prim's extents by converting the ECEF AABB to a local USD AABB. That would happen in [`OmniTileset::updateTransform`](https://github.com/CesiumGS/cesium-omniverse/blob/824e9283cd9efa17ee9d75b0fe4760ba658b1b84/src/core/src/OmniTileset.cpp#L345-L364).

Once this is all set you should be able to click the tileset in the outliner, press the `F` key, and have it zoom to the proper extents.

We can start by implementing this without setting the georeference origin, though the suspect the camera will appear rotated.

**Comment by lilleyse** [comment]
> Convert the bounding volume to an axis-aligned box in ECEF coordinates. Check if there's helper functions for doing this in cesium-native, otherwise check what exists in CesiumJS.

On second thought, I think a better approach is to convert the bounding volume (`box`, `region`, or `sphere`) to an oriented bounding box, not an axis-aligned bounding box. This will lead to a more conservative bounding volume. Plus it's simpler to implement.

* For `region` take a look at [`BoundingRegion`](https://github.com/CesiumGS/cesium-native/blob/405e8519a4af91307805897fa4813103dec56b8a/CesiumGeospatial/src/BoundingRegion.cpp). It already does this, we just need a public getter for `_boundingBox`.
* For `box` it's already an oriented bounding box. No extra math required.
* For `sphere` you can get the corner points and rotate them so they're aligned with the surface normal. [`getEastNorthUpToFixedFrame`](https://github.com/CesiumGS/cesium-omniverse/blob/e1183b8744e961d3ae73e1aa4a9f3506c8e6a299/src/core/src/UsdUtil.cpp#LL24C12-L24C38) should give you the transformation matrix to do that.

**Comment by corybarr** [comment]
> 

Current I'm using `auto oriented = Cesium3DTilesSelection::getOrientedBoundingBoxFromBoundingVolume(boundingVolume);`  The volume std::variant seems to abstract away having to deal with any specific type of volume.

**Comment by lilleyse** [comment]
@corybarr Oh nice find! Looks like a recent addition to cesium-native that I must have missed.
