### ISSUE TITLE
Console warnings

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium-omniverse#241]
Our extension prints several serious looking but harmless warning messages. We should fix these.

![image](https://user-images.githubusercontent.com/915398/226767528-d1b7c79f-00b5-4a58-8699-5d0ef11ce622.png)

**Comment by weegeekps** [comment]
So, I figured out that the error coming from `cesium.omniverse.extension` was a logic error which I've got a fix for, but I'm not sure what we can really do about some of the others. 

Regarding the `carb.flatcache.plugin` errors, I suspect that the issue is actually within the Fabric code. The calls in `setProjectDefaultToken` are the only calls prior to that first warning about `cesium:projectDefaultIonAccessToken`. When we make those calls no errors are immediately written. I see two possibilities here, either the logging buffer hasn't written yet, or Fabric itself is creating those errors. I find the latter more likely, as the logging buffer tends to be immediate in Omniverse.

Another thing I noticed is that it seems to switch between `cesium:projectDefaultIonAccessToken` and `cesium:projectDefaultIonAccessTokenId`, which also gives a hint it may be threading related, but when I sit down with breakpoints and make sure everything is in the correct order it is.

Also, the final error I think happens without our plugin enabled.
