### ISSUE TITLE
stray white tile that won't deload

### ISSUE THREAD

**Issue by mattelser** [CesiumGS/cesium-omniverse#335]
possibly related to #334. @corybarr first noticed this yesterday and I was able to reproduce it today on linux and windows.
![Screenshot from 2023-06-09 17-12-41](https://github.com/CesiumGS/cesium-omniverse/assets/62680156/308c8b91-e894-4f9e-9f8c-aa47cb5cd4b0)

Cory suggested 
> Dangling tile references maybe? I wonder if they're in Fabric because nothing in the USD stage disables it.

Notably, as can be seen in the image above, the tile does not deload when zoomed in on.

**Comment by lilleyse** [comment]
I can't reproduce this in Kit 105 during normal usage. I think because we're use a geometry pool there and never actually destroying prims.

However I can trigger this 100% of the time when clicking "Disable Geometry Pool" in the `/Cesium` settings. This clears the pools and destroys the fabric prims, leaving white tiles behind. Interestingly, the white tiles are those that were previously visible.

I don't think we have a leak because if you comment out the "Repopulate the asset registry" block in `reloadStage` and click "Print Fabric stage" in the Cesium Debugging window, the stage doesn't doesn't have any pool-related prims.


https://github.com/CesiumGS/cesium-omniverse/assets/915398/ab80ffa3-c1b4-4aa7-aea5-3f23a2ebf826

**Comment by lilleyse** [comment]
I'm pretty sure the issue above was caused by me removing the `/TempChangeTracking` code thinking it was no longer needed in Kit 105. That's fixed in https://github.com/CesiumGS/cesium-omniverse/pull/389.
