### ISSUE TITLE
Use `rel` for imagery layers

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium-omniverse#585]
Currently imagery layers are child prims of a tileset, but it would make more sense for them to be components of a tileset like in Cesium for Unreal and Unity. We might be able to use a `multipleApply` schema for this. This would be a breaking change, so we should try to do it in the same release as the imagery related breaking changes for tileset clipping.

Some questions:

* Can the order of imagery layers be rearranged in the UI when using `multipleApply` schema?

CC @weegeekps @corybarr

**Comment by weegeekps** [comment]
The main issue I see here is that the order of a multi apply schema doesn't really have meaning within USD and I don't believe it to be stable. 

The correct way to do within USD this is to leave imagery as a Concrete IsA schema but use a relationship binding for this. Relationship bindings are always stable lists.

**Comment by corybarr** [comment]
Right now we're using parent-child relationships for imagery layers. It sounds like the plan is to stick with that for a bit. I got curious about Multiple-Apply API Schemas after reading the [Generating New Schema Classes](https://openusd.org/release/tut_generating_new_schema.html) doc. It seemed to fit the need very well, but I'm not so sure now. The doc lists `UsdCollectionAPI` as a multiple-apply schema, but I don't know the use case for it.

What I really like about an API over a `rel` is that the UI becomes much more content-creator friendly. Everything related is in a nice, collapsible section instead of piled into the raw USD properties. This seems solvable, and there's likely a way to do something analogous to a Unity [Custom Inspector](https://docs.unity3d.com/Manual/UIE-HowTo-CreateCustomInspector.html) script to re-style the editor UI.

**Comment by lilleyse** [comment]
One other benefit of relationships is that multiple tilesets could reference the same imagery prim instead of duplicating the imagery prim for each.

**Comment by lilleyse** [comment]
Using `rel` should fix https://github.com/CesiumGS/cesium-omniverse/issues/586
