### ISSUE TITLE
Use `rel` for CesiumCartographicPolygon

### ISSUE THREAD

**Issue by lilleyse** [CesiumGS/cesium-omniverse#639]
Based on discussion in https://github.com/CesiumGS/cesium-omniverse/issues/632 there a few disadvantages of `CesiumCartographicPolygon` being a subclass of `BasisCurves`. We should consider using `rel` instead.

**Comment by r-veenstra** [comment]
Decisions from standup

- Prefered UX approach is to keep a single `CesiumCartographicPolygon`prim, vs splitting into two
- @corybarr will look further into isolating the issue
- If we can't figure it out prior to release, we'll likely update `CesiumPolygonRasterOverlay` to support pointing directly to `BasisCurve` + `Globe Anchor` combo, rather than the `rel`approach to keep UX simple
- `CesiumPolygonRasterOverlay` can be re-added at a later time if needed

**Comment by corybarr** [comment]
> * @corybarr will look further into isolating the issue

Having created a minimal example that does touch our codebase, I don't think we can keep a single `CesiumCartographicPolygon` prim for this release.
